In [15]:
import pandas as pd
import numpy as np


In [16]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,17]],columns=['CGPA','PROFILE_SCORE','LPA'])

In [17]:
df

,CGPA,PROFILE_SCORE,LPA
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,17


In [18]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [19]:
model=Sequential()

In [20]:
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.get_weights()

[array([[-0.2861219 ,  0.26360536],
        [-0.2604742 ,  0.06275856]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.7682642 ],
        [0.22183299]], dtype=float32),
 array([0.], dtype=float32)]

In [23]:
new_weights=[np.array([[0.1,0.1],
                       [0.1,0.1]],dtype=np.float32),
np.array([0.,0.],dtype=np.float32),
np.array([[0.1],[0.1]],dtype=np.float32),
np.array([0.],dtype=np.float32)]

In [24]:
model.set_weights(new_weights)

In [25]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [29]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [33]:
model.fit(df.iloc[:,0:-1].values,df['LPA'],epochs=200,verbose=1,batch_size=1)

Epoch 1/200
4/4 [==============================] - 0s 2ms/step - loss: 24.6787
Epoch 2/200
4/4 [==============================] - 0s 4ms/step - loss: 24.6818
Epoch 3/200
4/4 [==============================] - 0s 6ms/step - loss: 24.6699
Epoch 4/200
4/4 [==============================] - 0s 3ms/step - loss: 24.6270
Epoch 5/200
4/4 [==============================] - 0s 8ms/step - loss: 24.6264
Epoch 6/200
4/4 [==============================] - 0s 5ms/step - loss: 24.6043
Epoch 7/200
4/4 [==============================] - 0s 3ms/step - loss: 24.5837
Epoch 8/200
4/4 [==============================] - 0s 3ms/step - loss: 24.5690
Epoch 9/200
4/4 [==============================] - 0s 10ms/step - loss: 24.5656
Epoch 10/200
4/4 [==============================] - 0s 4ms/step - loss: 24.5803
Epoch 11/200
4/4 [==============================] - 0s 2ms/step - loss: 24.5248
Epoch 12/200
4/4 [==============================] - 0s 2ms/step - loss: 24.5215
Epoch 13/200
4/4 [==============================

In [35]:
model.get_weights()

[array([[0.26219308, 0.26219308],
        [0.58724177, 0.58724177]], dtype=float32),
 array([0.35626566, 0.35626566], dtype=float32),
 array([[0.50731254],
        [0.50731254]], dtype=float32),
 array([0.26477683], dtype=float32)]

In [ ]:
optimizer=keras.optimizers.Adam