In [3]:
import numpy as np
import pandas as pd

In [4]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,17]],columns=['CGPA','PROFILE_SCORE','LPA'])

In [5]:
df.head()

,CGPA,PROFILE_SCORE,LPA
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,17


In [6]:
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [7]:
X=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [8]:
model=Sequential()

In [9]:
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.get_weights()

[array([[-0.36545855,  0.32411957],
        [ 0.07561648,  0.37449682]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.9743633 ],
        [ 0.35203612]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights=[np.array([[0.1,0.1],
                       [0.1,0.1]],dtype=np.float32),
np.array([0.,0.],dtype=np.float32),
np.array([[0.1],[0.1]],dtype=np.float32),
np.array([0.],dtype=np.float32)]

In [13]:
model.set_weights(new_weights)

In [14]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
optimizer=keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='mean_absolute_error',optimizer=optimizer)

In [19]:
model.fit(df.iloc[:,0:-1].values,df['LPA'],epochs=200,verbose=1,batch_size=1)

Epoch 1/200
4/4 [==============================] - 1s 5ms/step - loss: 7.4466
Epoch 2/200
4/4 [==============================] - 0s 2ms/step - loss: 7.4152
Epoch 3/200
4/4 [==============================] - 0s 3ms/step - loss: 7.3846
Epoch 4/200
4/4 [==============================] - 0s 4ms/step - loss: 7.3554
Epoch 5/200
4/4 [==============================] - 0s 3ms/step - loss: 7.3278
Epoch 6/200
4/4 [==============================] - 0s 3ms/step - loss: 7.3017
Epoch 7/200
4/4 [==============================] - 0s 3ms/step - loss: 7.2774
Epoch 8/200
4/4 [==============================] - 0s 2ms/step - loss: 7.2547
Epoch 9/200
4/4 [==============================] - 0s 4ms/step - loss: 7.2338
Epoch 10/200
4/4 [==============================] - 0s 5ms/step - loss: 7.2147
Epoch 11/200
4/4 [==============================] - 0s 6ms/step - loss: 7.1972
Epoch 12/200
4/4 [==============================] - 0s 8ms/step - loss: 7.1813
Epoch 13/200
4/4 [==============================] - 0s 5ms/st

In [21]:
model.get_weights()

[array([[0.5089504 , 0.5089504 ],
        [0.51090163, 0.51090163]], dtype=float32),
 array([0.41506648, 0.41506648], dtype=float32),
 array([[1.9635084],
        [1.9635084]], dtype=float32),
 array([1.8193483], dtype=float32)]