How to choose the best model for given machine-learning problem or how to do hyper parameter tunning
for example we have iris flower dataset and predict the what type of flower it is there are so many model should we use 
random forest,svm,decision trees,logistic regression,naive bayes

In [1]:
from sklearn.svm import SVC

In [2]:
from sklearn.datasets import load_iris

In [4]:
iris=load_iris()

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
import pandas as pd


In [7]:
df=pd.DataFrame(iris['data'],columns=iris['feature_names'])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [20]:
df['Flower']=iris['target']
df['Flower']=df['Flower'].apply(lambda x:iris.target_names[x])

In [58]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [21]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [22]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        Flower  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(iris['data'],iris['target'],test_size=0.3)

Just assume that you are going to svm model

In [30]:
model=SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)


SVC(C=30, gamma='auto')

In [31]:
model.score(x_test,y_test)

0.9555555555555556

The result change in every itration so thats why we use k-fold cross validation 

we have a method of cross-val-score which can tell you the score of each itration here 

In [32]:
from sklearn.model_selection import cross_val_score

In [33]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),iris['data'],iris['target'],cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [34]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),iris['data'],iris['target'],cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [ ]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),iris['data'],iris['target'],cv=5)#cv means five fold

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [36]:
from sklearn.model_selection import GridSearchCV

In [37]:
clf=GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)#first parameter is your model,second the value of c,and third the value of kernel and at the end cv means cross validation =5
#once it is done you will do the model train 
clf.fit(iris['data'],iris['target'])
clf.cv_results_

{'mean_fit_time': array([0.00299864, 0.00320654, 0.00600033, 0.01039929, 0.00459757,
        0.00350413]),
 'std_fit_time': array([0.00063135, 0.00039301, 0.00296749, 0.01233838, 0.00287119,
        0.00252954]),
 'mean_score_time': array([0.00600429, 0.00359058, 0.00380106, 0.00360661, 0.0035996 ,
        0.00280237]),
 'std_score_time': array([0.00465271, 0.00048968, 0.00271305, 0.00327024, 0.00162709,
        0.00147328]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_s

cv result are not easy to view but sklearn provide a way to download these result into the dataframe 

In [38]:
df=pd.DataFrame(clf.cv_results_)

In [39]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.002999      0.000631         0.006004        0.004653        1   
1       0.003207      0.000393         0.003591        0.000490        1   
2       0.006000      0.002967         0.003801        0.002713       10   
3       0.010399      0.012338         0.003607        0.003270       10   
4       0.004598      0.002871         0.003600        0.001627       20   
5       0.003504      0.002530         0.002802        0.001473       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [41]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [43]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_run_sea

In [44]:
clf.best_score_

np.float64(0.9800000000000001)

In [45]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

high computational cost in gridcv to tackle this computational cost we use randomized search cv it will try a random combination of these parameters

In [46]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,
return_train_score=False,
n_iter=2)

In [47]:
rs.fit(iris['data'],iris['target'])
rs.cv_results_

{'mean_fit_time': array([0.00237851, 0.00282359]),
 'std_fit_time': array([0.00118979, 0.00079509]),
 'mean_score_time': array([0.0036552 , 0.00227017]),
 'std_score_time': array([0.00118033, 0.00054684]),
 'param_kernel': masked_array(data=['rbf', 'linear'],
              mask=[False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[20, 10],
              mask=[False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 20}, {'kernel': 'linear', 'C': 10}],
 'split0_test_score': array([0.96666667, 1.        ]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.9, 0.9]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.96666667, 0.97333333]),
 'std_test_score': array([0.03651484, 0.03887301]),
 'rank_test_score': array([2, 1], dtype=int32)}

In [48]:
df=pd.DataFrame(rs.cv_results_)

In [49]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.002379      0.001190         0.003655        0.001180          rbf   
1       0.002824      0.000795         0.002270        0.000547       linear   

   param_C                         params  split0_test_score  \
0       20     {'kernel': 'rbf', 'C': 20}           0.966667   
1       10  {'kernel': 'linear', 'C': 10}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0                0.9           0.966667                1.0   
1                1.0                0.9           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.966667        0.036515                2  
1         0.973333        0.038873                1

In [51]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       20          rbf         0.966667
1       10       linear         0.973333

Hyperparameter Tunning

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [54]:
model_params={
    'svm':{
        'model':SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'LogisticRegression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
    
}

In [55]:
score=[]

for model_name, mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(iris['data'],iris['target'])
    score.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_log

In [56]:
df=pd.DataFrame(score,columns=['model','best_score','best_params'])

In [57]:
df

model  best_score                best_params
0                 svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1       random_forest    0.953333        {'n_estimators': 5}
2  LogisticRegression    0.966667                   {'C': 5}