For digits dataset in sklearn.datasets,please try following classifier to find out the one that gives best performance.also find the optimal parameters for that classifier 

from sklearn.svc import svm 

from sklearn.ensambles import randomforesr

from sklearn.linear model import logisticregression 

from sklearn.naive_bayes import GaussainNb

from sklearn.naive_bayes import multinomialNB

from sklearn.tree import decisionTreeClassifier


There are many ways to find the best classifier 

The first one is crossvalidation

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_digits

In [4]:
logmodel=LogisticRegression()
svm=SVC()
rf=RandomForestClassifier()
nb=MultinomialNB()
nb1=GaussianNB()
tree=DecisionTreeClassifier()
digits=load_digits()

In [5]:
digits['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64))

In [6]:
digits['target']

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

In [8]:
df=pd.DataFrame(digits['data'],columns=digits['feature_names'])

In [9]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_5  pixel_7_6  pixel_7_7
0        0.0        0.0        5.0  ...        0.0        0.0        0.0
1        0.0        0.0        0.0  ...       10.0        0.0        0.0
2        0.0        0.0        0.0  ...       16.0        9.0        0.0
3        0.0        0.0        7.0  ...        9.0        0.0        0.0
4        0.0        0.0        0.0  ...        4.0        0.0        0.0

[5 rows x 64 columns]

In [10]:
df['Target']=digits['target']

In [11]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  Target
0        0.0        0.0        5.0  ...        0.0        0.0       0
1        0.0        0.0        0.0  ...        0.0        0.0       1
2        0.0        0.0        0.0  ...        9.0        0.0       2
3        0.0        0.0        7.0  ...        0.0        0.0       3
4        0.0        0.0        0.0  ...        0.0        0.0       4

[5 rows x 65 columns]

validation by train_test_split

In [12]:
x_train,x_test,y_train,x_test=train_test_split(digits['data'],digits['target'],test_size=0.3)

cross validation

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(SVC(kernel='rbf',gamma='auto',C=10),digits['data'],digits['target'],cv=5)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [17]:
cross_val_score(LogisticRegression(),digits['data'],digits['target'],cv=5)

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [22]:
cross_val_score(DecisionTreeClassifier(),digits['data'],digits['target'],cv=5)

array([0.78333333, 0.70555556, 0.80501393, 0.83286908, 0.78830084])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits['data'],digits['target'],cv=5)

array([0.89444444, 0.77777778, 0.89693593, 0.91922006, 0.84679666])

In [29]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),digits['data'],digits['target'],cv=5)#cv means five fold

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

It can also done with the gridsearchcv

In [27]:
from sklearn.model_selection import GridSearchCV

In [30]:
clf=GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)
#Now train the model
clf.fit(digits['data'],digits['target'])
clf.best_score_

np.float64(0.9476973073351903)

in gridsearchsv you must give the parameters 

In [32]:
clf1=GridSearchCV(LogisticRegression(max_iter=1000),{
    "C":[0.1,1,10],
    'solver':['liblinear','saga']
},cv=5,return_train_score=False)
clf1.fit(digits['data'],digits['target'])
clf1.best_score_

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\R.C\.conda\envs\

np.float64(0.9243423088826989)

In gridSearchsv it has high computational cost so we overcome this computational cost by random search cv it is similer to the gridsearchcv

In [33]:
from sklearn.model_selection import RandomizedSearchCV

In [35]:
rf=RandomizedSearchCV(LogisticRegression(max_iter=1000),{
    'C':[1,10,20],
    'solver':['liblinear','saga']
},cv=5,return_train_score=False)
rf.fit(digits['data'],digits['target'])
rf.best_score_

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ 

np.float64(0.9221138966264315)

if we have more models so we use this type of coding

In [41]:
model_params={
    'LogisticRegression':{
        'model':LogisticRegression(solver="liblinear",multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    },
    'SVM':{
        'model':SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':["rbf",'linear']
        }
    },
    'RandomForestClassifier':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10 ]
        }
    },
    'MultinomialNB':{
        'model':MultinomialNB(alpha=1.0),
        'params':{
            'fit_prior':[True,False]

        }
    },
    'GaussianNB':{
        'model':GaussianNB(),
        'params':{
           # 'priors':[[0.5,0.3,0.2]]
        }
    },
    'Decision_Tree':{
        'model':DecisionTreeClassifier(criterion='entropy'),
        'params':{
            'max_depth':[5,10],
            'min_samples_split':[2,5,10]
        }
    }
}

In [42]:
score=[]

for model_name, mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(digits['data'],digits['target'])
    score.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_log

In [45]:
df=pd.DataFrame(score,columns=['model','best_score','best_params'])

In [46]:
df

model  ...                                best_params
0      LogisticRegression  ...                                   {'C': 1}
1                     SVM  ...               {'C': 1, 'kernel': 'linear'}
2  RandomForestClassifier  ...                       {'n_estimators': 10}
3           MultinomialNB  ...                        {'fit_prior': True}
4              GaussianNB  ...                                         {}
5           Decision_Tree  ...  {'max_depth': 10, 'min_samples_split': 2}

[6 rows x 3 columns]