Train svm classifier using sklearn digits dataset(i.e from sklearn.load_datasets import load_digits)then:


Measure accuracy of your model using different kernals passing(like:rbf and linear)

Tune your model using regulariztion and gama parameters and try to come up with highest accuracy score
use 80% of sample as traing data size

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits

In [3]:
digits=load_digits()

In [4]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [5]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [6]:
digits['feature_names']
print('/n')
digits['frame']

/n


In [7]:
digits['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]], shape=(1797, 64))

In [8]:
digits['target_names']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
df=pd.DataFrame(digits['data'],columns=digits['feature_names'])

In [10]:
len(digits['data'])

1797

In [11]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [12]:
digits['target']

array([0, 1, 2, ..., 8, 9, 8], shape=(1797,))

In [13]:
df['target']=digits['target']

In [14]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [15]:
df.tail()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        0.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        0.0        0.0   

      pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
1792        0.0        2.0       14.0       15.0        9.0        0.0   
1793        0.0        6.0       16.0       14.0        6.0        0.0   
1794        0.0        2.0        9.0       13.0        6.0        0.0   
1795        0.0        5.0       12.0       16.0       12.0        0.0   
1796        1.0        8.0       12.0       14.0       12.0        1.0   

      pixel_7_7  target  
1792        0.0       9  
1793        0.0       0  
1794        0.0       8  
1795        0.0       9  
1796        0.0       8  

[5 rows x 65 columns]

In [16]:
df[df['target']==1].head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
1         0.0        0.0        0.0       12.0       13.0        5.0   
11        0.0        0.0        0.0        0.0       14.0       13.0   
21        0.0        0.0        0.0        2.0       16.0       16.0   
42        0.0        0.0        0.0        0.0       12.0        5.0   
47        0.0        0.0        0.0        1.0       11.0        9.0   

    pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
1         0.0        0.0        0.0        0.0  ...        0.0        0.0   
11        1.0        0.0        0.0        0.0  ...        0.0        0.0   
21        2.0        0.0        0.0        0.0  ...        0.0        0.0   
42        0.0        0.0        0.0        0.0  ...        0.0        0.0   
47        0.0        0.0        0.0        0.0  ...        0.0        0.0   

    pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
1         0.0        0.0       11.0       16.0       10.0        0.0   
11        0.0        0.0        1.0       13.0       16.0        1.0   
21        0.0        0.0        2.0       12.0       15.0        4.0   
42        0.0        0.0        3.0       16.0        8.0        0.0   
47        0.0        0.0        2.0       14.0        6.0        0.0   

    pixel_7_7  target  
1         0.0       1  
11        0.0       1  
21        0.0       1  
42        0.0       1  
47        0.0       1  

[5 rows x 65 columns]

In [17]:
df[df['target']==9].head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
9         0.0        0.0       11.0       12.0        0.0        0.0   
19        0.0        0.0        6.0       14.0        4.0        0.0   
29        0.0        0.0        9.0       13.0        7.0        0.0   
31        0.0        0.0        2.0       13.0        8.0        0.0   
37        0.0        0.0       13.0       10.0        1.0        0.0   

    pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
9         0.0        0.0        0.0        2.0  ...        0.0        0.0   
19        0.0        0.0        0.0        0.0  ...        2.0        0.0   
29        0.0        0.0        0.0        0.0  ...        2.0        0.0   
31        0.0        0.0        0.0        0.0  ...        2.0        0.0   
37        0.0        0.0        0.0        5.0  ...        0.0        0.0   

    pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
9         0.0        9.0       12.0       13.0        3.0        0.0   
19        0.0        7.0       16.0       16.0       13.0       11.0   
29        0.0        7.0       12.0       12.0       12.0       11.0   
31        0.0        2.0       15.0       13.0       14.0       13.0   
37        0.0       13.0       13.0       15.0       16.0       13.0   

    pixel_7_7  target  
9         0.0       9  
19        1.0       9  
29        0.0       9  
31        2.0       9  
37        0.0       9  

[5 rows x 65 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797 entries, 0 to 1796
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pixel_0_0  1797 non-null   float64
 1   pixel_0_1  1797 non-null   float64
 2   pixel_0_2  1797 non-null   float64
 3   pixel_0_3  1797 non-null   float64
 4   pixel_0_4  1797 non-null   float64
 5   pixel_0_5  1797 non-null   float64
 6   pixel_0_6  1797 non-null   float64
 7   pixel_0_7  1797 non-null   float64
 8   pixel_1_0  1797 non-null   float64
 9   pixel_1_1  1797 non-null   float64
 10  pixel_1_2  1797 non-null   float64
 11  pixel_1_3  1797 non-null   float64
 12  pixel_1_4  1797 non-null   float64
 13  pixel_1_5  1797 non-null   float64
 14  pixel_1_6  1797 non-null   float64
 15  pixel_1_7  1797 non-null   float64
 16  pixel_2_0  1797 non-null   float64
 17  pixel_2_1  1797 non-null   float64
 18  pixel_2_2  1797 non-null   float64
 19  pixel_2_3  1797 non-null   float64
 20  pixel_2_

In [19]:
digits['target_names']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

datframe is for the scatter plot

In [20]:
df0=df[df['target']==0]
df1=df[df['target']==1]
df2=df[df['target']==2]

In [21]:
df0.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0         0.0        0.0        5.0       13.0        9.0        1.0   
10        0.0        0.0        1.0        9.0       15.0       11.0   
20        0.0        0.0        3.0       13.0       11.0        7.0   
30        0.0        0.0       10.0       14.0       11.0        3.0   
36        0.0        0.0        6.0       14.0       10.0        2.0   

    pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0         0.0        0.0        0.0        0.0  ...        0.0        0.0   
10        0.0        0.0        0.0        0.0  ...        0.0        0.0   
20        0.0        0.0        0.0        0.0  ...        0.0        0.0   
30        0.0        0.0        0.0        4.0  ...        0.0        0.0   
36        0.0        0.0        0.0        0.0  ...        0.0        0.0   

    pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0         0.0        6.0       13.0       10.0        0.0        0.0   
10        0.0        1.0       10.0       13.0        3.0        0.0   
20        0.0        2.0       12.0       13.0        4.0        0.0   
30        0.0       11.0       16.0       12.0        3.0        0.0   
36        0.0        7.0       16.0       11.0        1.0        0.0   

    pixel_7_7  target  
0         0.0       0  
10        0.0       0  
20        0.0       0  
30        0.0       0  
36        0.0       0  

[5 rows x 65 columns]

In [22]:
from sklearn.model_selection import train_test_split 

In [23]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [24]:
x=df.drop(['target'],axis=1)


In [25]:
x.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [26]:
y=df['target']

In [27]:
y.head()

0    0
1    1
2    2
3    3
4    4
Name: target, dtype: int64

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [29]:
len(x_train)

1437

In [30]:
len(x_test)

360

In [31]:
from sklearn.svm import SVC

In [32]:
model=SVC(kernel='linear')

In [33]:
model.fit(x_train,y_train)

SVC(kernel='linear')

In [34]:
model.score(x_test,y_test)

0.9833333333333333

checking with kernals and gama parameters and arguments and check the accuracy of the model by different regularization

In [35]:
model=SVC(C=10)

In [36]:
model.fit(x_train,y_train)

SVC(C=10)

In [37]:
model.score(x_test,y_test)

0.9916666666666667

In [38]:
model=SVC(kernel='linear')

In [39]:
model.fit(x_test,y_test)

SVC(kernel='linear')

In [40]:
model.score(x_test,y_test)

1.0

In [41]:
model=SVC(gamma=2)

In [42]:
model.fit(x_train,y_train)

SVC(gamma=2)

In [43]:
model.score(x_test,y_test)

0.07777777777777778