We have 100 samples of data,in this techniue K-fold_cross_validation we divide our 100 samples of data into folds like 5 folds each containing 20 samples and then you run multiple iteration,In the first itration we use fold number 2 to 5 for training the model and fold number 1 for test the model,In the second itration we use 1st fold and three to five for training and the 2nd fold is for testing,in the third itration we use 1st,2nd,4th,5th for training the model and and third one is for testing and so on till the fold 5th.collect the score of every itration and arranging them out.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
from sklearn.datasets import load_digits

In [5]:
digits=load_digits()

In [6]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

split that dataset into training and testing 

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
x=digits['data']
y=digits['target']

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=101)

We can use a different classifier for example first classifier are used is LogisticRegression

In [11]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

Example:Svm

In [14]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9888888888888889

Example:Random_forest 

In [16]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=40)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9740740740740741

Use K-fold api to demonstrate.n_split i which you are specify how many folds you want to create

In [17]:
from sklearn.model_selection import KFold

In [24]:
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

Use the kfold on the dataset

In [25]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Create a method to simplify the thing for the itration

In [26]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [27]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [28]:
get_score(SVC(),x_train,x_test,y_train,y_test)


0.9888888888888889

In [29]:
get_score(RandomForestClassifier(n_estimators=10),x_train,x_test,y_train,y_test)

0.9518518518518518

In [30]:
from sklearn.model_selection import StratifiedKFold

StartifiedKFold is similar to K-Fold but it is little better in a way that when you are seprating out your force.it will devide each of the classification catagories in unifoam way

In [31]:
fold=StratifiedKFold(n_splits=3)

Working on the real Dataset

In [35]:
score_l= []
score_svm= []
score_rf= []
for train_index,test_index in kf.split(digits['data']):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

In [36]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [37]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [38]:
score_rf

[0.9382303839732888, 0.9565943238731218, 0.9282136894824707]

In [40]:
from sklearn.model_selection import cross_val_score

cross_val_score(first argument is your classifier,second argument is your x,third argument is your y)

In [41]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

Parameter tunning

In [42]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [43]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93333333, 0.91388889, 0.95821727, 0.96100279, 0.9275766 ])