Take the iris flower dataset and use different classifier rf,svm,logistic regression,decision tree and use cross val score method to measure the performance of the best classifier 

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [4]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

Many ways to do the work on different classifier

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x=iris['data']
y=iris['target']

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=101)

we use different classifier one by one but its time costly and long term process

In [8]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

In [9]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9777777777777777

In [10]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9555555555555556

In [11]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [12]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

In [13]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9777777777777777

In [14]:
get_score(RandomForestClassifier(n_estimators=10),x_train,x_test,y_train,y_test)

0.9333333333333333

By using k-fold-cross validation,in a manuall way

In [15]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [16]:
score_l=[]
score_svc=[]
score_rf=[]
for train_index,test_index in kf.split(iris['data']):
    x_train,x_test,y_train,y_test=iris.data[train_index],iris.data[test_index],iris.target[train_index],iris.target[test_index]
    score_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svc.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

In [17]:
score_l

[0.0, 0.0, 0.0]

In [18]:
score_rf

[0.0, 0.0, 0.0]

In [19]:
score_svc

[0.0, 0.0, 0.0]

We also do this with one line of code 

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(LogisticRegression(),iris.data,iris.target)

c:\Users\R.C\.conda\envs\Machine_Learning\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [22]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [23]:
cross_val_score(RandomForestClassifier(n_estimators=3),iris.data,iris.target)

array([1.        , 0.96666667, 0.83333333, 0.93333333, 1.        ])

Measure the accuracy with K-Fold-Cross-Validation